<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.11" />
        <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.2" />
        <PackageReference Include="StackExchange.Redis" Version="3.0.11" />
        <PackageReference Include="Testcontainers" Version="4.13.0" />
        <PackageReference Include="Testcontainers.MsSql" Version="4.13.0" />
        <PackageReference Include="Testcontainers.Redis" Version="4.13.0" />
        <PackageReference Include="TUnit.Core" Version="1.58.0" />
        <PackageReference Include="WireMock.Net" Version="2.12.0" />
        <PackageReference Include="WireMock.Net.RestClient" Version="2.12.0" />
        <PackageReference Include="WireMock.Net.Testcontainers" Version="2.12.0" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="../MERRICK.DatabaseContext/MERRICK.DatabaseContext.csproj" />
    </ItemGroup>

</Project>
