using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MERRICK.DatabaseContext.Migrations
{
    /// <inheritdoc />
    public partial class AddMasteries : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Masteries",
                schema: "stat",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AccountID = table.Column<int>(type: "int", nullable: false),
                    Hero_Accursed_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Adrenaline_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Aluna_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Andromeda_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Apex_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Arachna_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Armadon_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Artesia_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Artillery_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_BabaYaga_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Behemoth_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Bephelgor_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Berzerker_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Blitz_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Bombardier_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Bubbles_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Bushwack_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Calamity_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Chipper_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Chi_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Chronos_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Circe_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_CorruptedDisciple_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Cthulhuphant_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Dampeer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Deadlift_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Deadwood_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Defiler_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Devourer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_DiseasedRider_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_DoctorRepulsor_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Dreadknight_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_DrunkenMaster_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_DwarfMagi_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Ebulus_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Electrician_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Ellonia_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_EmeraldWarden_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Empath_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Engineer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Fade_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Fairy_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_FlameDragon_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_FlintBeastwood_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Flux_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_ForsakenArcher_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Frosty_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Gauntlet_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Gemini_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Geomancer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Gladiator_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Goldenveil_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Grinex_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Gunblade_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Hammerstorm_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Hantumon_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Hellbringer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_HellDemon_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Hiro_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Hunter_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Hydromancer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Ichor_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Javaras_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Jereziah_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Kane_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Kenisis_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_KingKlout_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Klanx_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Kraken_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Krixi_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Kunas_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Legionnaire_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Lodestone_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Magmar_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Maliken_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Martyr_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_MasterOfArms_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Midas_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Mimix_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Moira_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Monarch_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_MonkeyKing_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Moraxus_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Mumra_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Nitro_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Nomad_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Oogie_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Ophelia_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Panda_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Parallax_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Parasite_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Pearl_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Pestilence_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Plant_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_PollywogPriest_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Predator_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Prisoner_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Prophet_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_PuppetMaster_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Pyromancer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Rally_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Rampage_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Ravenor_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Ra_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Revenant_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Rhapsody_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Riftmage_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Riptide_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Rocky_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Salomon_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_SandWraith_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Sapphire_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Scar_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Scout_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_ShadowBlade_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Shaman_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Shellshock_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Silhouette_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_SirBenzington_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Skrap_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Solstice_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Soulstealer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Succubis_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Taint_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Tarot_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Tempest_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Treant_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Tremble_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Tundra_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Valkyrie_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Vanya_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Vindicator_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Voodoo_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Warchief_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_WitchSlayer_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_WolfMan_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Xalynx_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Yogi_XP = table.Column<int>(type: "int", nullable: false),
                    Hero_Zephyr_XP = table.Column<int>(type: "int", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Masteries", x => x.ID);
                    table.ForeignKey(
                        name: "FK_Masteries_Accounts_AccountID",
                        column: x => x.AccountID,
                        principalSchema: "core",
                        principalTable: "Accounts",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateTable(
                name: "MasteryRewards",
                schema: "stat",
                columns: table => new
                {
                    ID = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    AccountID = table.Column<int>(type: "int", nullable: false),
                    Obtained_0001 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0002 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0003 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0005 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0007 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0010 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0015 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0020 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0025 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0030 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0035 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0040 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0045 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0050 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0055 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0060 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0065 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0070 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0075 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0080 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0085 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0090 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0095 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0100 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0105 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0110 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0115 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0120 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0125 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0130 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0135 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0140 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0145 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0150 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0155 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0160 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0165 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0170 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0175 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0180 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0185 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0190 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0195 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0200 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0205 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0210 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0215 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0220 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0225 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0230 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0235 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0240 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0245 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0250 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0255 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0260 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0265 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0270 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0275 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0280 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0285 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0290 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0295 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0300 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0305 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0310 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0315 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0320 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0325 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0330 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0335 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0340 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0345 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0350 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0355 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0360 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0365 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0370 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0375 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0380 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0385 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0390 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0395 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0400 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0405 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0410 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0415 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0420 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0425 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0430 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0435 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0440 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0445 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0450 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0455 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0460 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0465 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0470 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0475 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0480 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0485 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0490 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0495 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0500 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0505 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0510 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0515 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0520 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0525 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0530 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0535 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0540 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0545 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0550 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0555 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0560 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0565 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0570 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0575 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0580 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0585 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0590 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0595 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0600 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0605 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0610 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0615 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0620 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0625 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0630 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0635 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0640 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0645 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0650 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0655 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0660 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0665 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0670 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0675 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0680 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0685 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0690 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0695 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0700 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0705 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0710 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0715 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0720 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0725 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0730 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0735 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0740 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0745 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0750 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0755 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0760 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0765 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0770 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0775 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0780 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0785 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0790 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0795 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0800 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0805 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0810 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0815 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0820 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0825 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0830 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0835 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0840 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0845 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0850 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0855 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0860 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0865 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0870 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0875 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0880 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0885 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0890 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0895 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0900 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0905 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0910 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0915 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0920 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0925 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0930 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0935 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0940 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0945 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0950 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0955 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0960 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0965 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0970 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0975 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0980 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0985 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0990 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_0995 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1000 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1005 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1010 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1015 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1020 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1025 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1030 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1035 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1040 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1045 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1050 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1055 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1060 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1065 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1070 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1075 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1080 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1085 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1090 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1095 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1100 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1105 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1110 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1115 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1120 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1125 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1130 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1135 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1140 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1145 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1150 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1155 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1160 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1165 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1170 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1175 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1180 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1185 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1190 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1195 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1200 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1205 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1210 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1215 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1220 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1225 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1230 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1235 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1240 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1245 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1250 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1255 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1260 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1265 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1270 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1275 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1280 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1285 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1290 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1295 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1300 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1305 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1310 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1315 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1320 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1325 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1330 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1335 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1340 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1345 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1350 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1355 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1360 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1365 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1370 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1375 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1380 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1385 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1390 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1395 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1400 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1405 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1410 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1415 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1420 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1425 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1430 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1435 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1440 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1445 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1450 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1455 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1460 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1465 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1470 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1475 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1480 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1485 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1490 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1495 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1500 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1505 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1510 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1515 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1520 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1525 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1530 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1535 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1540 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1545 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1550 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1555 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1560 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1565 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1570 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1575 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1580 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1585 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1590 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1595 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1600 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1605 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1610 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1615 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1620 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1625 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1630 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1635 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1640 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1645 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1650 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1655 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1660 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1665 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1670 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1675 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1680 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1685 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1690 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1695 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1700 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1705 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1710 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1715 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1720 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1725 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1730 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1735 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1740 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1745 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1750 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1755 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1760 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1765 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1770 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1775 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1780 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1785 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1790 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1795 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1800 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1805 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1810 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1815 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1820 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1825 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1830 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1835 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1840 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1845 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1850 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1855 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1860 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1865 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1870 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1875 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1880 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1885 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1890 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1895 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1900 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1905 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1910 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1915 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1920 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1925 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1930 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1935 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1940 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1945 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1950 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1955 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1960 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1965 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1970 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1975 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1980 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1985 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1990 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_1995 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2000 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2005 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2010 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2015 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2020 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2025 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2030 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2035 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2040 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2045 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2050 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2055 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2060 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2065 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2070 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2075 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2080 = table.Column<bool>(type: "bit", nullable: false),
                    Obtained_2085 = table.Column<bool>(type: "bit", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_MasteryRewards", x => x.ID);
                    table.ForeignKey(
                        name: "FK_MasteryRewards_Accounts_AccountID",
                        column: x => x.AccountID,
                        principalSchema: "core",
                        principalTable: "Accounts",
                        principalColumn: "ID",
                        onDelete: ReferentialAction.Cascade);
                });

            migrationBuilder.CreateIndex(
                name: "IX_Masteries_AccountID",
                schema: "stat",
                table: "Masteries",
                column: "AccountID",
                unique: true);

            migrationBuilder.CreateIndex(
                name: "IX_MasteryRewards_AccountID",
                schema: "stat",
                table: "MasteryRewards",
                column: "AccountID",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Masteries",
                schema: "stat");

            migrationBuilder.DropTable(
                name: "MasteryRewards",
                schema: "stat");
        }
    }
}
