namespace MERRICK.DatabaseContext.Entities.Statistics;

/// <summary>
///     Tracks which total mastery level reward tiers an account has already claimed.
///     There is one flag per reward tier, named "Obtained_" followed by the required total mastery level padded to four digits (for example "Obtained_0015").
///     The reward content for each tier is defined in the mastery rewards configuration. This entity records only whether each tier has been claimed.
/// </summary>
[Index(nameof(AccountID), IsUnique = true)]
public class MasteryRewards
{
    [Key]
    public int ID { get; set; }

    public int AccountID { get; set; }

    [ForeignKey(nameof(AccountID))]
    public required Account Account { get; set; }

    /// <summary>
    ///     Whether the reward tier for the given total mastery level has already been claimed.
    /// </summary>
    public bool HasObtained(int level)
    {
        PropertyInfo? property = GetType().GetProperties().SingleOrDefault(property => property.Name == $"Obtained_{level:D4}");

        return property is not null && Convert.ToBoolean(property.GetValue(this));
    }

    /// <summary>
    ///     Marks the reward tier for the given total mastery level as claimed.
    /// </summary>
    /// <returns>
    ///     <see langword="true"/> if the reward tier exists and was marked as claimed, otherwise <see langword="false"/>.
    /// </returns>
    public bool MarkObtained(int level)
    {
        PropertyInfo? property = GetType().GetProperties().SingleOrDefault(property => property.Name == $"Obtained_{level:D4}");

        if (property is null)
            return false;

        property.SetValue(this, true);

        return true;
    }

    public bool Obtained_0001 { get; set; }
    public bool Obtained_0002 { get; set; }
    public bool Obtained_0003 { get; set; }
    public bool Obtained_0005 { get; set; }
    public bool Obtained_0007 { get; set; }
    public bool Obtained_0010 { get; set; }
    public bool Obtained_0015 { get; set; }
    public bool Obtained_0020 { get; set; }
    public bool Obtained_0025 { get; set; }
    public bool Obtained_0030 { get; set; }
    public bool Obtained_0035 { get; set; }
    public bool Obtained_0040 { get; set; }
    public bool Obtained_0045 { get; set; }
    public bool Obtained_0050 { get; set; }
    public bool Obtained_0055 { get; set; }
    public bool Obtained_0060 { get; set; }
    public bool Obtained_0065 { get; set; }
    public bool Obtained_0070 { get; set; }
    public bool Obtained_0075 { get; set; }
    public bool Obtained_0080 { get; set; }
    public bool Obtained_0085 { get; set; }
    public bool Obtained_0090 { get; set; }
    public bool Obtained_0095 { get; set; }
    public bool Obtained_0100 { get; set; }
    public bool Obtained_0105 { get; set; }
    public bool Obtained_0110 { get; set; }
    public bool Obtained_0115 { get; set; }
    public bool Obtained_0120 { get; set; }
    public bool Obtained_0125 { get; set; }
    public bool Obtained_0130 { get; set; }
    public bool Obtained_0135 { get; set; }
    public bool Obtained_0140 { get; set; }
    public bool Obtained_0145 { get; set; }
    public bool Obtained_0150 { get; set; }
    public bool Obtained_0155 { get; set; }
    public bool Obtained_0160 { get; set; }
    public bool Obtained_0165 { get; set; }
    public bool Obtained_0170 { get; set; }
    public bool Obtained_0175 { get; set; }
    public bool Obtained_0180 { get; set; }
    public bool Obtained_0185 { get; set; }
    public bool Obtained_0190 { get; set; }
    public bool Obtained_0195 { get; set; }
    public bool Obtained_0200 { get; set; }
    public bool Obtained_0205 { get; set; }
    public bool Obtained_0210 { get; set; }
    public bool Obtained_0215 { get; set; }
    public bool Obtained_0220 { get; set; }
    public bool Obtained_0225 { get; set; }
    public bool Obtained_0230 { get; set; }
    public bool Obtained_0235 { get; set; }
    public bool Obtained_0240 { get; set; }
    public bool Obtained_0245 { get; set; }
    public bool Obtained_0250 { get; set; }
    public bool Obtained_0255 { get; set; }
    public bool Obtained_0260 { get; set; }
    public bool Obtained_0265 { get; set; }
    public bool Obtained_0270 { get; set; }
    public bool Obtained_0275 { get; set; }
    public bool Obtained_0280 { get; set; }
    public bool Obtained_0285 { get; set; }
    public bool Obtained_0290 { get; set; }
    public bool Obtained_0295 { get; set; }
    public bool Obtained_0300 { get; set; }
    public bool Obtained_0305 { get; set; }
    public bool Obtained_0310 { get; set; }
    public bool Obtained_0315 { get; set; }
    public bool Obtained_0320 { get; set; }
    public bool Obtained_0325 { get; set; }
    public bool Obtained_0330 { get; set; }
    public bool Obtained_0335 { get; set; }
    public bool Obtained_0340 { get; set; }
    public bool Obtained_0345 { get; set; }
    public bool Obtained_0350 { get; set; }
    public bool Obtained_0355 { get; set; }
    public bool Obtained_0360 { get; set; }
    public bool Obtained_0365 { get; set; }
    public bool Obtained_0370 { get; set; }
    public bool Obtained_0375 { get; set; }
    public bool Obtained_0380 { get; set; }
    public bool Obtained_0385 { get; set; }
    public bool Obtained_0390 { get; set; }
    public bool Obtained_0395 { get; set; }
    public bool Obtained_0400 { get; set; }
    public bool Obtained_0405 { get; set; }
    public bool Obtained_0410 { get; set; }
    public bool Obtained_0415 { get; set; }
    public bool Obtained_0420 { get; set; }
    public bool Obtained_0425 { get; set; }
    public bool Obtained_0430 { get; set; }
    public bool Obtained_0435 { get; set; }
    public bool Obtained_0440 { get; set; }
    public bool Obtained_0445 { get; set; }
    public bool Obtained_0450 { get; set; }
    public bool Obtained_0455 { get; set; }
    public bool Obtained_0460 { get; set; }
    public bool Obtained_0465 { get; set; }
    public bool Obtained_0470 { get; set; }
    public bool Obtained_0475 { get; set; }
    public bool Obtained_0480 { get; set; }
    public bool Obtained_0485 { get; set; }
    public bool Obtained_0490 { get; set; }
    public bool Obtained_0495 { get; set; }
    public bool Obtained_0500 { get; set; }
    public bool Obtained_0505 { get; set; }
    public bool Obtained_0510 { get; set; }
    public bool Obtained_0515 { get; set; }
    public bool Obtained_0520 { get; set; }
    public bool Obtained_0525 { get; set; }
    public bool Obtained_0530 { get; set; }
    public bool Obtained_0535 { get; set; }
    public bool Obtained_0540 { get; set; }
    public bool Obtained_0545 { get; set; }
    public bool Obtained_0550 { get; set; }
    public bool Obtained_0555 { get; set; }
    public bool Obtained_0560 { get; set; }
    public bool Obtained_0565 { get; set; }
    public bool Obtained_0570 { get; set; }
    public bool Obtained_0575 { get; set; }
    public bool Obtained_0580 { get; set; }
    public bool Obtained_0585 { get; set; }
    public bool Obtained_0590 { get; set; }
    public bool Obtained_0595 { get; set; }
    public bool Obtained_0600 { get; set; }
    public bool Obtained_0605 { get; set; }
    public bool Obtained_0610 { get; set; }
    public bool Obtained_0615 { get; set; }
    public bool Obtained_0620 { get; set; }
    public bool Obtained_0625 { get; set; }
    public bool Obtained_0630 { get; set; }
    public bool Obtained_0635 { get; set; }
    public bool Obtained_0640 { get; set; }
    public bool Obtained_0645 { get; set; }
    public bool Obtained_0650 { get; set; }
    public bool Obtained_0655 { get; set; }
    public bool Obtained_0660 { get; set; }
    public bool Obtained_0665 { get; set; }
    public bool Obtained_0670 { get; set; }
    public bool Obtained_0675 { get; set; }
    public bool Obtained_0680 { get; set; }
    public bool Obtained_0685 { get; set; }
    public bool Obtained_0690 { get; set; }
    public bool Obtained_0695 { get; set; }
    public bool Obtained_0700 { get; set; }
    public bool Obtained_0705 { get; set; }
    public bool Obtained_0710 { get; set; }
    public bool Obtained_0715 { get; set; }
    public bool Obtained_0720 { get; set; }
    public bool Obtained_0725 { get; set; }
    public bool Obtained_0730 { get; set; }
    public bool Obtained_0735 { get; set; }
    public bool Obtained_0740 { get; set; }
    public bool Obtained_0745 { get; set; }
    public bool Obtained_0750 { get; set; }
    public bool Obtained_0755 { get; set; }
    public bool Obtained_0760 { get; set; }
    public bool Obtained_0765 { get; set; }
    public bool Obtained_0770 { get; set; }
    public bool Obtained_0775 { get; set; }
    public bool Obtained_0780 { get; set; }
    public bool Obtained_0785 { get; set; }
    public bool Obtained_0790 { get; set; }
    public bool Obtained_0795 { get; set; }
    public bool Obtained_0800 { get; set; }
    public bool Obtained_0805 { get; set; }
    public bool Obtained_0810 { get; set; }
    public bool Obtained_0815 { get; set; }
    public bool Obtained_0820 { get; set; }
    public bool Obtained_0825 { get; set; }
    public bool Obtained_0830 { get; set; }
    public bool Obtained_0835 { get; set; }
    public bool Obtained_0840 { get; set; }
    public bool Obtained_0845 { get; set; }
    public bool Obtained_0850 { get; set; }
    public bool Obtained_0855 { get; set; }
    public bool Obtained_0860 { get; set; }
    public bool Obtained_0865 { get; set; }
    public bool Obtained_0870 { get; set; }
    public bool Obtained_0875 { get; set; }
    public bool Obtained_0880 { get; set; }
    public bool Obtained_0885 { get; set; }
    public bool Obtained_0890 { get; set; }
    public bool Obtained_0895 { get; set; }
    public bool Obtained_0900 { get; set; }
    public bool Obtained_0905 { get; set; }
    public bool Obtained_0910 { get; set; }
    public bool Obtained_0915 { get; set; }
    public bool Obtained_0920 { get; set; }
    public bool Obtained_0925 { get; set; }
    public bool Obtained_0930 { get; set; }
    public bool Obtained_0935 { get; set; }
    public bool Obtained_0940 { get; set; }
    public bool Obtained_0945 { get; set; }
    public bool Obtained_0950 { get; set; }
    public bool Obtained_0955 { get; set; }
    public bool Obtained_0960 { get; set; }
    public bool Obtained_0965 { get; set; }
    public bool Obtained_0970 { get; set; }
    public bool Obtained_0975 { get; set; }
    public bool Obtained_0980 { get; set; }
    public bool Obtained_0985 { get; set; }
    public bool Obtained_0990 { get; set; }
    public bool Obtained_0995 { get; set; }
    public bool Obtained_1000 { get; set; }
    public bool Obtained_1005 { get; set; }
    public bool Obtained_1010 { get; set; }
    public bool Obtained_1015 { get; set; }
    public bool Obtained_1020 { get; set; }
    public bool Obtained_1025 { get; set; }
    public bool Obtained_1030 { get; set; }
    public bool Obtained_1035 { get; set; }
    public bool Obtained_1040 { get; set; }
    public bool Obtained_1045 { get; set; }
    public bool Obtained_1050 { get; set; }
    public bool Obtained_1055 { get; set; }
    public bool Obtained_1060 { get; set; }
    public bool Obtained_1065 { get; set; }
    public bool Obtained_1070 { get; set; }
    public bool Obtained_1075 { get; set; }
    public bool Obtained_1080 { get; set; }
    public bool Obtained_1085 { get; set; }
    public bool Obtained_1090 { get; set; }
    public bool Obtained_1095 { get; set; }
    public bool Obtained_1100 { get; set; }
    public bool Obtained_1105 { get; set; }
    public bool Obtained_1110 { get; set; }
    public bool Obtained_1115 { get; set; }
    public bool Obtained_1120 { get; set; }
    public bool Obtained_1125 { get; set; }
    public bool Obtained_1130 { get; set; }
    public bool Obtained_1135 { get; set; }
    public bool Obtained_1140 { get; set; }
    public bool Obtained_1145 { get; set; }
    public bool Obtained_1150 { get; set; }
    public bool Obtained_1155 { get; set; }
    public bool Obtained_1160 { get; set; }
    public bool Obtained_1165 { get; set; }
    public bool Obtained_1170 { get; set; }
    public bool Obtained_1175 { get; set; }
    public bool Obtained_1180 { get; set; }
    public bool Obtained_1185 { get; set; }
    public bool Obtained_1190 { get; set; }
    public bool Obtained_1195 { get; set; }
    public bool Obtained_1200 { get; set; }
    public bool Obtained_1205 { get; set; }
    public bool Obtained_1210 { get; set; }
    public bool Obtained_1215 { get; set; }
    public bool Obtained_1220 { get; set; }
    public bool Obtained_1225 { get; set; }
    public bool Obtained_1230 { get; set; }
    public bool Obtained_1235 { get; set; }
    public bool Obtained_1240 { get; set; }
    public bool Obtained_1245 { get; set; }
    public bool Obtained_1250 { get; set; }
    public bool Obtained_1255 { get; set; }
    public bool Obtained_1260 { get; set; }
    public bool Obtained_1265 { get; set; }
    public bool Obtained_1270 { get; set; }
    public bool Obtained_1275 { get; set; }
    public bool Obtained_1280 { get; set; }
    public bool Obtained_1285 { get; set; }
    public bool Obtained_1290 { get; set; }
    public bool Obtained_1295 { get; set; }
    public bool Obtained_1300 { get; set; }
    public bool Obtained_1305 { get; set; }
    public bool Obtained_1310 { get; set; }
    public bool Obtained_1315 { get; set; }
    public bool Obtained_1320 { get; set; }
    public bool Obtained_1325 { get; set; }
    public bool Obtained_1330 { get; set; }
    public bool Obtained_1335 { get; set; }
    public bool Obtained_1340 { get; set; }
    public bool Obtained_1345 { get; set; }
    public bool Obtained_1350 { get; set; }
    public bool Obtained_1355 { get; set; }
    public bool Obtained_1360 { get; set; }
    public bool Obtained_1365 { get; set; }
    public bool Obtained_1370 { get; set; }
    public bool Obtained_1375 { get; set; }
    public bool Obtained_1380 { get; set; }
    public bool Obtained_1385 { get; set; }
    public bool Obtained_1390 { get; set; }
    public bool Obtained_1395 { get; set; }
    public bool Obtained_1400 { get; set; }
    public bool Obtained_1405 { get; set; }
    public bool Obtained_1410 { get; set; }
    public bool Obtained_1415 { get; set; }
    public bool Obtained_1420 { get; set; }
    public bool Obtained_1425 { get; set; }
    public bool Obtained_1430 { get; set; }
    public bool Obtained_1435 { get; set; }
    public bool Obtained_1440 { get; set; }
    public bool Obtained_1445 { get; set; }
    public bool Obtained_1450 { get; set; }
    public bool Obtained_1455 { get; set; }
    public bool Obtained_1460 { get; set; }
    public bool Obtained_1465 { get; set; }
    public bool Obtained_1470 { get; set; }
    public bool Obtained_1475 { get; set; }
    public bool Obtained_1480 { get; set; }
    public bool Obtained_1485 { get; set; }
    public bool Obtained_1490 { get; set; }
    public bool Obtained_1495 { get; set; }
    public bool Obtained_1500 { get; set; }
    public bool Obtained_1505 { get; set; }
    public bool Obtained_1510 { get; set; }
    public bool Obtained_1515 { get; set; }
    public bool Obtained_1520 { get; set; }
    public bool Obtained_1525 { get; set; }
    public bool Obtained_1530 { get; set; }
    public bool Obtained_1535 { get; set; }
    public bool Obtained_1540 { get; set; }
    public bool Obtained_1545 { get; set; }
    public bool Obtained_1550 { get; set; }
    public bool Obtained_1555 { get; set; }
    public bool Obtained_1560 { get; set; }
    public bool Obtained_1565 { get; set; }
    public bool Obtained_1570 { get; set; }
    public bool Obtained_1575 { get; set; }
    public bool Obtained_1580 { get; set; }
    public bool Obtained_1585 { get; set; }
    public bool Obtained_1590 { get; set; }
    public bool Obtained_1595 { get; set; }
    public bool Obtained_1600 { get; set; }
    public bool Obtained_1605 { get; set; }
    public bool Obtained_1610 { get; set; }
    public bool Obtained_1615 { get; set; }
    public bool Obtained_1620 { get; set; }
    public bool Obtained_1625 { get; set; }
    public bool Obtained_1630 { get; set; }
    public bool Obtained_1635 { get; set; }
    public bool Obtained_1640 { get; set; }
    public bool Obtained_1645 { get; set; }
    public bool Obtained_1650 { get; set; }
    public bool Obtained_1655 { get; set; }
    public bool Obtained_1660 { get; set; }
    public bool Obtained_1665 { get; set; }
    public bool Obtained_1670 { get; set; }
    public bool Obtained_1675 { get; set; }
    public bool Obtained_1680 { get; set; }
    public bool Obtained_1685 { get; set; }
    public bool Obtained_1690 { get; set; }
    public bool Obtained_1695 { get; set; }
    public bool Obtained_1700 { get; set; }
    public bool Obtained_1705 { get; set; }
    public bool Obtained_1710 { get; set; }
    public bool Obtained_1715 { get; set; }
    public bool Obtained_1720 { get; set; }
    public bool Obtained_1725 { get; set; }
    public bool Obtained_1730 { get; set; }
    public bool Obtained_1735 { get; set; }
    public bool Obtained_1740 { get; set; }
    public bool Obtained_1745 { get; set; }
    public bool Obtained_1750 { get; set; }
    public bool Obtained_1755 { get; set; }
    public bool Obtained_1760 { get; set; }
    public bool Obtained_1765 { get; set; }
    public bool Obtained_1770 { get; set; }
    public bool Obtained_1775 { get; set; }
    public bool Obtained_1780 { get; set; }
    public bool Obtained_1785 { get; set; }
    public bool Obtained_1790 { get; set; }
    public bool Obtained_1795 { get; set; }
    public bool Obtained_1800 { get; set; }
    public bool Obtained_1805 { get; set; }
    public bool Obtained_1810 { get; set; }
    public bool Obtained_1815 { get; set; }
    public bool Obtained_1820 { get; set; }
    public bool Obtained_1825 { get; set; }
    public bool Obtained_1830 { get; set; }
    public bool Obtained_1835 { get; set; }
    public bool Obtained_1840 { get; set; }
    public bool Obtained_1845 { get; set; }
    public bool Obtained_1850 { get; set; }
    public bool Obtained_1855 { get; set; }
    public bool Obtained_1860 { get; set; }
    public bool Obtained_1865 { get; set; }
    public bool Obtained_1870 { get; set; }
    public bool Obtained_1875 { get; set; }
    public bool Obtained_1880 { get; set; }
    public bool Obtained_1885 { get; set; }
    public bool Obtained_1890 { get; set; }
    public bool Obtained_1895 { get; set; }
    public bool Obtained_1900 { get; set; }
    public bool Obtained_1905 { get; set; }
    public bool Obtained_1910 { get; set; }
    public bool Obtained_1915 { get; set; }
    public bool Obtained_1920 { get; set; }
    public bool Obtained_1925 { get; set; }
    public bool Obtained_1930 { get; set; }
    public bool Obtained_1935 { get; set; }
    public bool Obtained_1940 { get; set; }
    public bool Obtained_1945 { get; set; }
    public bool Obtained_1950 { get; set; }
    public bool Obtained_1955 { get; set; }
    public bool Obtained_1960 { get; set; }
    public bool Obtained_1965 { get; set; }
    public bool Obtained_1970 { get; set; }
    public bool Obtained_1975 { get; set; }
    public bool Obtained_1980 { get; set; }
    public bool Obtained_1985 { get; set; }
    public bool Obtained_1990 { get; set; }
    public bool Obtained_1995 { get; set; }
    public bool Obtained_2000 { get; set; }
    public bool Obtained_2005 { get; set; }
    public bool Obtained_2010 { get; set; }
    public bool Obtained_2015 { get; set; }
    public bool Obtained_2020 { get; set; }
    public bool Obtained_2025 { get; set; }
    public bool Obtained_2030 { get; set; }
    public bool Obtained_2035 { get; set; }
    public bool Obtained_2040 { get; set; }
    public bool Obtained_2045 { get; set; }
    public bool Obtained_2050 { get; set; }
    public bool Obtained_2055 { get; set; }
    public bool Obtained_2060 { get; set; }
    public bool Obtained_2065 { get; set; }
    public bool Obtained_2070 { get; set; }
    public bool Obtained_2075 { get; set; }
    public bool Obtained_2080 { get; set; }
    public bool Obtained_2085 { get; set; }
}
