<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>library</OutputType>
        <IsAspireSharedProject>true</IsAspireSharedProject>
    </PropertyGroup>

    <ItemGroup>
        <FrameworkReference Include="Microsoft.AspNetCore.App" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Http.Resilience" Version="10.7.0" />
        <PackageReference Include="Microsoft.Extensions.ServiceDiscovery" Version="10.7.0" />
        <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" Version="1.16.0" />
        <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.16.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.16.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Http" Version="1.16.0" />
        <PackageReference Include="OpenTelemetry.Instrumentation.Runtime" Version="1.16.0" />
        <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
        <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
        <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
        <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
        <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
    </ItemGroup>

</Project>
